### ISSUE TITLE
Links to old Colabs on Drive

### ISSUE THREAD

**Issue by andsteing** [matthias-wright/flaxmodels#1]
I noticed that some links (e.g. from the main [`README`](https://github.com/matthias-wright/flaxmodels/blob/main/README.md), or from [`gpt2/README.md`](https://github.com/matthias-wright/flaxmodels/blob/main/flaxmodels/gpt2/README.md)) still point to the old Colabs on Drive.

Could you update the links such that they all point to the new Colab paths on Github?

Thanks, Andreas

**Comment by matthias-wright** [comment]
Hi @andsteing, thanks for the heads-up! I changed it now.
