### ISSUE TITLE
Resnet18 demo gives `OSError: Unable to open file (file signature not found)` 

### ISSUE THREAD

**Issue by DevPranjal** [matthias-wright/flaxmodels#16]
Demo notebook: [flaxmodels/resnet/resnet_demo.ipynb](https://github.com/matthias-wright/flaxmodels/blob/main/flaxmodels/resnet/resnet_demo.ipynb)

Notebook executed on Google Colab (GPU runtime)

Descriptive error message:
```
UnfilteredStackTrace: OSError: Unable to open file (file signature not found)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)
```

**Comment by matthias-wright** [comment]
Hi @DevPranjal, I cannot reproduce this error. The notebook is working fine for me on Colab. What is the part of the code that caused this error for you?
Can you execute this command in the Colab and post the result here:
```
!ls /tmp/flaxmodels
```

**Comment by DevPranjal** [comment]
Hi @matthias-wright, sorry for the late response. The notebook was running fine on CPU runtime, but gave the above error on the GPU runtime (repeatedly). On checking again now, it seems to work well (reason unknown).

Thanks for building this library, helps a lot.

Closing the issue
