### ISSUE TITLE
How did you convert pytorch model weight to Flax?

### ISSUE THREAD

**Issue by riven314** [matthias-wright/flaxmodels#19]
From the doc string of ResNet18, I saw you have the following comments:
```
The pretrained parameters are taken from:
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
```

May I know how did you convert a PyTorch model weight into Flax? I ddin't find any reference that touch upon this area. Many thanks!

**Comment by matthias-wright** [comment]
Hi @riven314, I just wrote a HOWTO on converting PyTorch models to Flax. The [PR](https://github.com/google/flax/pull/1848) is still pending but you can already read it [here](https://flax--1848.org.readthedocs.build/en/1848/howtos/convert_pytorch_to_flax.html). Hope that helps!

**Comment by riven314** [comment]
Wow really appreciate that. I will take a look 
Many thanks!
