### ISSUE TITLE
Installation - Numpy version

### ISSUE THREAD

**Issue by phlippe** [matthias-wright/flaxmodels#25]
Hi @matthias-wright, thanks a lot for releasing this nice, complete package for pretrained models! I have recently used your package in a [tutorial](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial6/Transformers_and_MHAttention.html#Set-Anomaly-Detection) to extract features from a pre-trained ResNet34, and noticed that the pip installation of the package requires an old numpy version (v1.19.5, [setup.py, line 15](https://github.com/matthias-wright/flaxmodels/blob/main/setup.py#L15)). However, the current tensorflow package requires a newer numpy (>v1.21) and installing flaxmodels can break an existing tensorflow installation. In this case, Flax throws an error during import regarding checkpoints from tensorflow because tensorflow has been compiled with a different numpy version than flaxmodels overwrote. A re-installation of the newest numpy version fixes the issue. Is it possible to change the requirement of the numpy package to `>=` instead of `==`, similar to what is currently used for JAX and Flax?

**Comment by matthias-wright** [comment]
Hi @phlippe, thank you for pointing this out! I changed the constraint to >=, hopefully it works now.

**Comment by phlippe** [comment]
Hi @matthias-wright, thanks for the quick fix, it works now!
