### ISSUE TITLE
How to train styleGAN on Colab TPU for custom dataset?

### ISSUE THREAD

**Issue by waleedrazakhan92** [matthias-wright/flaxmodels#27]
How do i run the training on my custom dataset while utilizing colab TPU.

**Comment by matthias-wright** [comment]
Hi @waleedrazakhan92, I don't have access to TPUs right now. Check out [this](https://github.com/nyx-ai/stylegan2-flax-tpu) repository. The author's adopted the flaxmodels stylegan2 implementation for TPU training. Hope that helps!

**Comment by waleedrazakhan92** [comment]
@matthias-wright thankyou for clearing this.
