### ISSUE TITLE
More info about the weight preprocessing step

### ISSUE THREAD

**Issue by icysapphire** [matthias-wright/flaxmodels#28]
Hi,
Thanks for your very useful work!

It would be very interesting to experiment with other pretrained weights. I am particularly interested in self-supervised learning weights. E.g. https://github.com/facebookresearch/barlowtwins

Could you share the weight processing script and/or add the proposed weights?

Thank you again!

**Comment by matthias-wright** [comment]
Hi @icysapphire, I don't have a particular script for this. However, I wrote a guide on how to convert Pytorch models to Flax: https://flax.readthedocs.io/en/latest/advanced_topics/convert_pytorch_to_flax.html
Hope that helps!
