### ISSUE TITLE
StyleGAN2 `--fmap_base` only affects generator feature maps

### ISSUE THREAD

**Issue by MasterScrat** [matthias-wright/flaxmodels#29]
Hello Matthias,

We have noticed that adjusting the value of `--fmap_base` only affects the generator:

https://github.com/matthias-wright/flaxmodels/blob/0ec7f22bda80c3e3c475e976af92b838cbbc22d4/training/stylegan2/training.py#L78

but not the discriminator: 

https://github.com/matthias-wright/flaxmodels/blob/0ec7f22bda80c3e3c475e976af92b838cbbc22d4/training/stylegan2/training.py#L101

Is this intentional?

In the [StyleGAN 2 paper](https://arxiv.org/abs/1912.04958), both G and D receive increased capacity (bottom of page 7):

> This leads us to hypothesize that there is a capacity problem in our networks, which we test by doubling the number of feature maps in the highest-resolution layers of both networks.

> We double the number of feature maps in resolutions 64^2–1024^2 while keeping other parts of the networks unchanged. This increases the total number of trainable parameters in the generator by 22% (25M → 30M) and in the discriminator by 21% (24M → 29M).

**Comment by matthias-wright** [comment]
Hi @MasterScrat, thanks for pointing that out, I fixed it.
